### ISSUE TITLE
issue regarding run of notebook

### ISSUE THREAD

**Issue by Pragnath** [xtyangpsp/HypoInvPy#1]
hi, @xtyangpsp the work was good, i was just running the notebook, i just was stuck here could you please help me 

**while running the code** 
_# 1. produce parameter files for each testing initial depth.
hypparfiledir='input'
hypparfilelist=hc.generate_parfile(cfg,hypparfiledir,outdir=outputdir)

#2. Run hypoinverse with all parameter files.
hc.run_hypoinv(hypparfilelist)_

**i got the error** 

'---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 6
      3 hypparfilelist=hc.generate_parfile(cfg,hypparfiledir,outdir=outputdir)
      5 # 2. Run hypoinverse with all parameter files.
----> 6 hc.run_hypoinv(hypparfilelist)

File ~/.local/lib/python3.10/site-packages/hypoinvpy/core.py:253, in run_hypoinv(parfilelist, hyp_bin)
    250 def run_hypoinv(parfilelist,hyp_bin='hyp1.40'):
    251     for fhyp in parfilelist:
    252         # 2. run hypoinverse
--> 253         p = subprocess.Popen([hyp_bin], stdin=subprocess.PIPE,encoding='utf-8')
    254         s = "@{}".format(fhyp) + '\n'
    255         p.communicate(s)

File /usr/lib/python3.10/subprocess.py:971, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)
    967         if self.text_mode:
    968             self.stderr = io.TextIOWrapper(self.stderr,
    969                     encoding=encoding, errors=errors)
--> 971     self._execute_child(args, executable, preexec_fn, close_fds,
    972                         pass_fds, cwd, env,
    973                         startupinfo, creationflags, shell,
    974                         p2cread, p2cwrite,
    975                         c2pread, c2pwrite,
    976                         errread, errwrite,
    977                         restore_signals,
    978                         gid, gids, uid, umask,
    979                         start_new_session)
    980 except:
    981     # Cleanup if the child failed starting.
    982     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File /usr/lib/python3.10/subprocess.py:1863, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861     if errno_num != 0:
   1862         err_msg = os.strerror(errno_num)
-> 1863     raise child_exception_type(errno_num, err_msg, err_filename)
   1864 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'hyp1.40'

**i tried to give the directory path and tried to give the exe hyp1.40 from source directory but could figure out. 
if you don't mid could you please help out.**

**Comment by Pragnath** [comment]
sorry when i added the exe file to **/usr/bin** the issue solved

**Comment by Pragnath** [comment]
sorry when i added the exe file to **/usr/bin** the issue solved

**Comment by xtyangpsp** [comment]
good to hear that. yes, it needs to be in the system search path. thanks for using this little tool. there are no magnitude estimates yet. welcome to contribute.

**Comment by Pragnath** [comment]
> good to hear that. yes, it needs to be in the system search path. thanks for using this little tool. there are no magnitude estimates yet. welcome to contribute.

Glad to hear from you.

By the way, could you suggest any Deep learning models for magnitude estimation other than **MAGNET** ?

**Comment by xtyangpsp** [comment]
I don't know any Deep learning packages for magnitude estimates. HypoInverse has the capability of estimating the magnitude. However, when I implement the interface, the example phase arrival data from EQT doesn't seem to have proper amplitude information. I would love to hear if you found a way to enable the magnitude information in HypoInvPy. I will have a student coming this fall to work more on this.
